# "$schema" = 'https://starship.rs/config-schema.json'

# format = "$directory$fill$env_var$character"
# with line break
# format = """\
# $env_var\
# $directory\
# $fill\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $fill\
# $all\
# $line_break\
# $character"""

# without line break
format = """\
$env_var\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$all\
$character"""

add_newline = false

[line_break]
disabled = true

[battery]

[[battery.display]]
threshold = 70

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]

min_time = 100
show_milliseconds = true

[directory]
truncation_length = 4
truncate_to_repo = false

[env_var.SMARTTHINGS_PROFILE]
format = "[$env_value]($style) "
style = "green bold"

[fill]
symbol = ' '

[git_commit]
format = '[$hash$tag]($style) '
style = 'purple bold'

[git_branch]
# format = "[$symbol$branch(:$remote_branch)]($style)"

[git_metrics]
disabled = true
# format = "([|](white dimmed)[+$added]($added_style) )([-$deleted]($deleted_style))"
added_style = 'purple bold'
deleted_style = 'purple bold'

[git_state]

[git_status]
# disabled = true
format = '([$all_status$ahead_behind]($style) )'
style = 'purple bold'

[memory_usage]
threshold = 80
disabled = false

[nodejs]
format = " [$symbol($version )]($style)"

[package]
disabled = true




# # Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

# # Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 10

# # Disable the blank line at the start of the prompt
# add_newline = false

# # Set "foo" as custom color palette
# palette = "foo"

# # Define custom colors
# [palettes.foo]
# # Overwrite existing color
# blue = "21"
# # Define new color
# mustard = "#af8700"
